import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import { OurStoreProvider } from "@/store/OurStoreContext";
import '../components/BaseCss/base.css';
import "../assets/css/bootstrap.min.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <OurStoreProvider>
          <Header />
          {children}
          <Footer />
        </OurStoreProvider>
      </body>
    </html>
  );
}
